MS-313 Update to core v0.11
membraneframework/membrane_ffmpeg_swscale_plugin pull request #17
Opened 2022-12-05 15:07 UTC by Janix4000

2022-12-05 16:45 UTC, bblaszkow06 commented on lib/membrane_ffmpeg_swscale/scaler/scaler.ex
>                  type: :boolean,
The field type should be replaced with `spec`
```suggestion
                spec: boolean(),
```

Same goes for other options (GH does not allow me to comment on them)

2022-12-05 16:49 UTC, bblaszkow06 commented on lib/membrane_ffmpeg_swscale/scaler/scaler.ex
> +    raise(RuntimeError, "uninitialized state: Scaler did not receive stream_format")
Since Core 0.10, the caps (now stream format) are enforced and this can never happen - you can remove the clause of `handle_process`

2022-12-05 16:52 UTC, bblaszkow06 commented on lib/membrane_ffmpeg_swscale/scaler/scaler.ex
>          raise(RuntimeError, reason)
1. reason must be string
2. `RuntimeError` is the default
```suggestion
        raise inspect(reason)
```

2022-12-05 16:53 UTC, bblaszkow06 commented on lib/membrane_ffmpeg_swscale/scaler/scaler.ex
> +    {[end_of_stream: :output], state}
This is now equivalent to the default implementation, you can remove this function

2022-12-05 16:54 UTC, bblaszkow06 commented on mix.exs
> +  @version "0.11.0"
PLS update README as well

2022-12-05 16:55 UTC, bblaszkow06 commented on lib/membrane_ffmpeg_swscale/pixel_format_converter/converter.ex
> +    raise "A Buffer was received before any stream format arrived. Cannot proceed"
Function can be removed

2022-12-05 16:57 UTC, bblaszkow06 commented on test/pixel_format_converter/converter_test.exs
> +    assert_end_of_stream(pipeline, :sink, :input, 10_000)
That's a leftover from our tests, it should pass with the default timeout
```suggestion
    assert_end_of_stream(pipeline, :sink)
```

2022-12-09 11:12 UTC, bblaszkow06 requested changes

2022-12-09 11:12 UTC, bblaszkow06 commented on lib/membrane_ffmpeg_swscale/scaler/scaler.ex
>    end
You haven't resolved https://github.com/membraneframework/membrane_ffmpeg_swscale_plugin/pull/17#discussion_r1039841910

2022-12-09 11:12 UTC, bblaszkow06 commented on lib/membrane_ffmpeg_swscale/pixel_format_converter/converter.ex
> +    raise "A Buffer was received before any stream format arrived. Cannot proceed"
bump

2022-12-09 11:12 UTC, bblaszkow06 commented on lib/membrane_ffmpeg_swscale/scaler/scaler.ex
> +    {[end_of_stream: :output], state}
bump

2022-12-20 13:04 UTC, Janix4000 commented
The diff is not working correctly. Please, look at the newest code directly (you can use `.`).

2022-12-23 14:47 UTC, bblaszkow06 approved these changes

2022-12-28 12:18 UTC, merged